trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  displayName: 'Install Node.js'
  inputs:
    version: '20.x'

- script: |
    node -v
    npm -v
    npm install
    npm run build
  displayName: 'Install dependencies and build'

- task: ArchiveFiles@2
  displayName: 'Create ZIP Package'
  inputs:
    rootFolderOrFile: 'dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/react-app.zip'
    replaceExistingArchive: true

- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: 'Azure subscription 1'
    appType: 'webAppLinux'
    appName: 'res'
    package: '$(Build.ArtifactStagingDirectory)/react-app.zip'